# Generated by Django 3.0.1 on 2021-07-07 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210706_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Тут должно быть название', max_length=50)),
                ('description', models.TextField(default='Тут должно быть описание')),
                ('dateStart', models.DateField(default=datetime.datetime(2021, 7, 7, 17, 38, 29, 805206))),
                ('dateEnd', models.DateField(default=datetime.datetime(2021, 7, 7, 17, 38, 29, 805206))),
                ('preview', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Hackaton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Тут должно быть название', max_length=50)),
                ('description', models.TextField(default='Тут должно быть описание')),
                ('date', models.DateField(default=datetime.datetime(2021, 7, 7, 17, 38, 29, 804206))),
                ('preview', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='tourtaiment',
            name='place',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 17, 38, 29, 802206)),
        ),
        migrations.AlterField(
            model_name='project',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 17, 38, 29, 803206)),
        ),
        migrations.AlterField(
            model_name='project',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 17, 38, 29, 803206)),
        ),
        migrations.AlterField(
            model_name='tourtaiment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 17, 38, 29, 804206)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 17, 38, 29, 803206)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 17, 38, 29, 803206)),
        ),
    ]
